import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Alert } from 'react-native';
import { ExportDateRange, ExportPreferences } from './storage';
import { ProduceBatch } from '../types';
import { formatDate, formatCurrency } from './formatters';

const RANGE_DAYS: Record<ExportDateRange, number | null> = { ALL: null, '30D': 30, '90D': 90 };

// Applies the user's Export Preferences date range to any list of records
// with a date field, so every report (batches, purchases, bookings,
// transactions) respects the same setting consistently.
export function filterByDateRange<T>(items: T[], getDate: (item: T) => string, range: ExportDateRange): T[] {
  const days = RANGE_DAYS[range];
  if (days == null) return items;
  const cutoff = Date.now() - days * 24 * 60 * 60 * 1000;
  return items.filter((item) => new Date(getDate(item)).getTime() >= cutoff);
}

export interface ReportRow {
  label: string;
  value: string;
}

export interface ReportSection {
  title: string;
  rows: ReportRow[];
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function buildReportHtml(title: string, subtitle: string, sections: ReportSection[]): string {
  const sectionsHtml = sections
    .map((section) => {
      const rowsHtml = section.rows.length
        ? section.rows
            .map(
              (row) => `
                <tr>
                  <td class="label">${escapeHtml(row.label)}</td>
                  <td class="value">${escapeHtml(row.value)}</td>
                </tr>`
            )
            .join('')
        : `<tr><td colspan="2" class="empty">No records.</td></tr>`;
      return `
        <h2>${escapeHtml(section.title)}</h2>
        <table>${rowsHtml}</table>`;
    })
    .join('');

  return `
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1C1C1C; padding: 24px; }
          .header { border-bottom: 3px solid #1A6B2E; padding-bottom: 12px; margin-bottom: 20px; }
          .brand { font-size: 22px; font-weight: 800; color: #1A6B2E; }
          .title { font-size: 18px; font-weight: 700; margin-top: 8px; }
          .subtitle { font-size: 12px; color: #6B7280; margin-top: 2px; }
          h2 { font-size: 14px; color: #1A6B2E; margin-top: 22px; margin-bottom: 8px; }
          table { width: 100%; border-collapse: collapse; }
          td { padding: 8px 4px; font-size: 12px; border-bottom: 1px solid #E5E7EB; }
          td.label { color: #6B7280; width: 55%; }
          td.value { color: #1C1C1C; font-weight: 600; text-align: right; }
          td.empty { color: #9CA3AF; font-style: italic; text-align: center; }
          .footer { margin-top: 32px; font-size: 10px; color: #9CA3AF; text-align: center; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="brand">AgroChain</div>
          <div class="title">${escapeHtml(title)}</div>
          <div class="subtitle">${escapeHtml(subtitle)}</div>
        </div>
        ${sectionsHtml}
        <div class="footer">Generated by AgroChain on ${escapeHtml(new Date().toLocaleString())}</div>
      </body>
    </html>`;
}

// Shared by both the buyer's produce detail screen and the farmer's batch
// detail screen — same underlying record, same report shape either way.
export function buildBatchReportSections(batch: ProduceBatch, prefs: ExportPreferences): ReportSection[] {
  const detailRows: ReportRow[] = [
    { label: 'Crop', value: batch.cropName },
    ...(batch.variety ? [{ label: 'Variety', value: batch.variety }] : []),
    { label: 'Quantity', value: `${batch.quantityKg} kg` },
    { label: 'Location', value: `${batch.district}, ${batch.region}` },
    { label: 'Status', value: batch.status.replace(/_/g, ' ') },
    { label: 'Farmer', value: batch.farmerName },
    { label: 'QR Code', value: batch.qrCodeValue },
  ];
  if (prefs.includePrices && batch.pricePerKg != null) {
    detailRows.push({ label: 'Price', value: `${formatCurrency(batch.pricePerKg)}/kg` });
  }
  if (prefs.includeDates) {
    if (batch.plantedDate) detailRows.push({ label: 'Planted', value: formatDate(batch.plantedDate) });
    if (batch.harvestedDate) detailRows.push({ label: 'Harvested', value: formatDate(batch.harvestedDate) });
    detailRows.push({ label: 'Logged', value: formatDate(batch.createdAt) });
  }

  const timelineRows: ReportRow[] = batch.processingStages.map((stage) => ({
    label: prefs.includeDates ? `${stage.stageName} (${formatDate(stage.timestamp)})` : stage.stageName,
    value: stage.description || stage.location || '—',
  }));

  return [
    { title: 'Batch Details', rows: detailRows },
    { title: 'Processing Timeline', rows: timelineRows },
  ];
}

// Renders the report to a PDF file on-device, then opens the native share
// sheet (save to Files, send via WhatsApp/email, print, etc.) — no backend
// involved, works offline.
export async function exportReportPdf(title: string, subtitle: string, sections: ReportSection[]): Promise<void> {
  try {
    const html = buildReportHtml(title, subtitle, sections);
    const { uri } = await Print.printToFileAsync({ html });
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: title });
    } else {
      Alert.alert('Report Ready', `Saved to ${uri}`);
    }
  } catch (err) {
    console.log('[pdfReport] export failed:', err);
    Alert.alert('Error', 'Could not generate the PDF report. Please try again.');
  }
}
